app:
  name: svc
  image:
    repository: "onecx/onecx-user-profile-svc"
  db:
    enabled: true
  operator:
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx:tenant:read ]
